#!/bin/bash

BATTERY=($(ls /sys/class/power_supply | grep BAT))
AC_ADAPTER=($(ls /sys/class/power_supply | grep AC))

if [[ -e "/sys/class/power_supply/${BATTERY[0]}/capacity" ]]; then
  level=$(cat /sys/class/power_supply/${BATTERY[0]}/capacity)
  ac=$(cat /sys/class/power_supply/${AC_ADAPTER[0]}/online)
fi

if [[ $level != "" ]]; then
  outstr=""
  
  if [[ $ac == "1" ]]; then
    outstr="${outstr}AC+:"
  else
    outstr="${outstr}BAT:"
  fi
  
  if [[ $level < "15" && $level != "100" ]]; then
    notify-send 'Low Battery' 'Your battery is below 15%.'
  fi
   
  outstr="${outstr}${level}%"
  
  echo $outstr
fi
