#!/bin/bash

track=$(mpc -f "[[%artist% - ]%title%]|[%file%]" current)
mpcstat=$(mpc)
status=$(echo $mpcstat | grep -oE "(\[p)(laying|aused)\]*")
time=$(echo $mpcstat | grep -oE "([0-9]+)\:([0-9]+)/([0-9]+)\:([0-9]+)")

if [[ "${status}" == "[playing]" ]]; then
  echo  ${track} - ${time}
elif [[ "${status}" == "[paused]" ]]; then
  echo  ${track} - ${time}
fi
