#!/bin/bash

if [[ $# -ne 1 ]]; then
  exit 1
fi

button=$1

case $button in
  1) mpc -p 6601 toggle # click
    ;;
  4) mpc -p 6601 prev # scroll up
    ;;
  5) mpc -p 6601 next # scroll down
    ;;
esac
