#!/bin/bash

if [[ $# -ne 1 ]]; then
  exit 1
fi

button=$1

case $button in
  1) playerctl play-pause || mpc -p 6601 toggle # click
    ;;
  4) playerctl previous || mpc -p 6601 prev # scroll up
    ;;
  5) playerctl next || mpc -p 6601 next # scroll down
    ;;
esac
