#!/bin/bash
TMP_AVI=$(mktemp /tmp/outXXXXX.avi)
ffcast -s % ffmpeg -y -f x11grab -show_region 1 -framerate 15 \
  -video_size %s -i %D+%c -codec:v huffyuv                    \
  -vf crop="iw-mod(iw\\,2):ih-mod(ih\\,2)" $TMP_AVI           
ffmpeg -i $TMP_AVI -pix_fmt rgb24 out.gif
convert -limit memory 1 -limit map 1 -layers Optimize out.gif out_optimized.gif
