#!/bin/bash

spotify_info(){
  sp_track=$(mpc -p 6601 -f "[[%artist% - ]%title%]|[%file%]" current)
  sp_mpcstat=$(mpc -p 6601)
  sp_status=$(echo $sp_mpcstat | grep -oE "(\[p)(laying|aused)\]*")
  sp_tracktime=$(echo $sp_mpcstat | grep -oE "([0-9]+)\:([0-9]+)/([0-9]+)\:([0-9]+)")
}

mpd_info(){
  mpd_track=$(mpc -f "[[%artist% - ]%title%]|[%file%]" current)
  mpd_mpcstat=$(mpc)
  mpd_status=$(echo $mpd_mpcstat | grep -oE "(\[p)(laying|aused)\]*")
  mpd_tracktime=$(echo $mpd_mpcstat | grep -oE "([0-9]+)\:([0-9]+)/([0-9]+)\:([0-9]+)")
}

playerctl_info(){
  player_title=$(playerctl metadata title)
  player_artist=$(playerctl metadata artist)
  player_track="${player_artist} - ${player_title}"
  player_status=$(playerctl status | grep -oE "(P)(laying|aused)")
}

mpd_info
spotify_info
playerctl_info

if [[ ! -z "${player_status}" ]]; then
  if [[ "${player_status}" == "Playing" ]]; then
    playstatus="[playing]"
  else
    playstatus="[paused]"
  fi
  track=${player_track}
elif [[ "${mpd_status}" == "[playing]" ]]; then
  playstatus=$mpd_status
  track=$mpd_track
  tracktime=$mpd_tracktime
elif [[ "${sp_status}" == "[playing]" || -z "${mpd_status}" ]]; then
  playstatus=$sp_status
  track=$sp_track
  tracktime=$sp_tracktime
fi

out=""

if [[ "${playstatus}" == "[playing]" ]]; then
  out=" ${track}"
elif [[ "${playstatus}" == "[paused]" ]]; then
  out=" ${track}"
fi

if [[ ! -z "${tracktime}" ]]; then
  out="${out} - ${tracktime}"
fi

echo $out
