#!/bin/bash

if type -P yay &> /dev/null ; then
  updateStr=$(~/.bin/yayupdates)
else
  updateStr=$(checkupdates)
fi

hasLinux=$(grep "linux" <<< ${updateStr})
updates=$(wc -l <<< ${updateStr})

if [[ -z ${updateStr} ]]; then
  updates=0
fi

if [[ ${hasLinux} ]]; then
  echo "⬆⟳ ${updates}"
else
  echo "⬆ ${updates}"
fi
